POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "12345"
POSTGRES_DB = "2gis_hack"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432

SQLALCHEMY_DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

